<template>
<div class="inset-0 flex items-center" :class="{'modal-container': modalLoading}">
    <div v-if="modalLoading" class="mx-auto">      
        <div class="loadingio-spinner-double-ring-t0xuu93cwm">
            <div class="ldio-20tj2v72mxrh">
                <div></div>
                <div></div>
                <div>
                    <div></div>
                </div>
                <div>
                    <div></div>
                </div>
            </div>
        </div>
    </div>
</div>
</template>
<script>
export default {
    name: "Spinner",
    props: ["modalLoading"],
}
</script>
<style scoped>
.modal-container{
    position: fixed;
    width: 100%;
    height: 100vh;
    z-index: 1000;
    background: rgba(0, 0, 0, 0.2);
}
</style>
<style type="text/css">
@keyframes ldio-20tj2v72mxrh {
    0% { transform: rotate(0) }
    100% { transform: rotate(360deg) }
}
.ldio-20tj2v72mxrh div { box-sizing: border-box!important }
.ldio-20tj2v72mxrh > div {
    position: absolute;
    width: 370.08px;
    height: 370.08px;
    top: 71.96px;
    left: 71.96px;
    border-radius: 50%;
    border: 41.12px solid #000;
    border-color: #2c5282 transparent #2c5282 transparent;
    animation: ldio-20tj2v72mxrh 1s linear infinite;
}

.ldio-20tj2v72mxrh > div:nth-child(2), .ldio-20tj2v72mxrh > div:nth-child(4) {
    width: 277.56px;
    height: 277.56px;
    top: 118.22px;
    left: 118.22px;
    animation: ldio-20tj2v72mxrh 1s linear infinite reverse;
}   
.ldio-20tj2v72mxrh > div:nth-child(2) {
    border-color: transparent #689cc5 transparent #689cc5
}
.ldio-20tj2v72mxrh > div:nth-child(3) { border-color: transparent }
.ldio-20tj2v72mxrh > div:nth-child(3) div {
    position: absolute;
    width: 100%;
    height: 100%;
    transform: rotate(45deg);
}
.ldio-20tj2v72mxrh > div:nth-child(3) div:before, .ldio-20tj2v72mxrh > div:nth-child(3) div:after { 
    content: "";
    display: block;
    position: absolute;
    width: 41.12px;
    height: 41.12px;
    top: -41.12px;
    left: 123.35999999999999px;
    background: #2c5282;
    border-radius: 50%;
    box-shadow: 0 328.96px 0 0 #2c5282;
}
.ldio-20tj2v72mxrh > div:nth-child(3) div:after {
    left: -41.12px;
    top: 123.35999999999999px;
    box-shadow: 328.96px 0 0 0 #2c5282;
}

.ldio-20tj2v72mxrh > div:nth-child(4) { border-color: transparent; }
.ldio-20tj2v72mxrh > div:nth-child(4) div {
    position: absolute;
    width: 100%;
    height: 100%;
    transform: rotate(45deg);
}
.ldio-20tj2v72mxrh > div:nth-child(4) div:before, .ldio-20tj2v72mxrh > div:nth-child(4) div:after {
    content: "";
    display: block;
    position: absolute;
    width: 41.12px;
    height: 41.12px;
    top: -41.12px;
    left: 77.1px;
    background: #689cc5;
    border-radius: 50%;
    box-shadow: 0 236.44px 0 0 #689cc5;
}
.ldio-20tj2v72mxrh > div:nth-child(4) div:after {
    left: -41.12px;
    top: 77.1px;
    box-shadow: 236.44px 0 0 0 #689cc5;
}
.loadingio-spinner-double-ring-t0xuu93cwm {
    width: 514px;
    height: 514px;
    display: inline-block;
    overflow: hidden;
    background: transparent;
}
.ldio-20tj2v72mxrh {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
}
.ldio-20tj2v72mxrh div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>